### ISSUE TITLE
Generación de Ganancias y pérdidas patrimoniales

### ISSUE THREAD

**Issue by tetreum** [vaijira/burocratin#1]
¡Pedazo curro te has hecho cabrón!

¿Planeas añadir también la opción de generar el output necesario para cumplimentar el apartado de Ganancias y pérdidas patrimoniales?
Es un coñazo de hacer cuando has hecho múltiples ventas

**Comment by vaijira** [comment]
Para degiro sería fácil porque lo incorpora en el informe. Para interactive brokers para movimientos de moneda extranjera sin tener movimientos de otros años no tengo claro cómo podría hacerse.

**Comment by tetreum** [comment]
No tiene que ver con esta issue, pero: ¿Dónde anda el css? No sé encontrarlo en el repo :S

Te dejo la propuesta que mejora un poquiiiiiiiiiiiiito la UI:
![image](https://user-images.githubusercontent.com/1708730/162785146-ba8043ba-01cf-431e-8d7f-7eae9b3b1a92.png)


```css
body {
    padding: 5px;
    font-family: Roboto, sans-serif;
}
.alert-warning {
    padding: 5px;
    color: #664d03;
    background-color: #fff3cd;
    border-color: #ffecb5;
    display: inline-block;
}
```

```html
<div class="alert-warning">
   <strong>Limitaciones</strong>
   <ul>
      <li>El modelo 720 generado se puede presentar si es la primera declaración o <a alt="720 FAQ" href="https://www.agenciatributaria.es/AEAT.internet/Inicio/Ayuda/Modelos__Procedimientos_y_Servicios/Ayuda_Modelo_720/Informacion_general/Preguntas_frecuentes__actualizadas_a_marzo_de_2014_/Nuevas_preguntas_frecuentes/Si_se_procede_a_la_venta_de_valores__articulo_42_ter_del_Reglamento_General_aprobado_por_el_RD_1065_2007___respecto_de_los_qu__on_de_informar_.shtml">si se ha realizado alguna venta y reinvertido el importe</a>.</li>
      <li>Sólo rellena información de acciones, no líquidez del broker.</li>
      <li>El código de país que usará para Degiro será NL y para interactive brokers IE.</li>
      <li>Modelo 720:Revisar el código de domiciliación del país, por defecto cogerá el del ISIN, pero esto no siempre es correcto.</li>
      <li>Modelo 720: Revisar la fecha de primera incorporación si tu primera transacción fue antes del año a declarar.</li>
   </ul>
</div>
```
